name: ci
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - scala: 2.12.14
          - scala: 2.13.6
          - scala: 3.0.1
          - scala: 3.0.2-RC1
          - scala: 3.0.3-RC1-bin-20210729-49d7399-NIGHTLY
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v12
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v6
    - run: sbt '++ ${{ matrix.scala }}!' compile
